### PR TITLE
ref(wkg): Cleanup of various parts of the wkg code

### PR DESCRIPTION
**Pull request by thomastaylor312**
This cleans up some usage of blocking IO in an async context as well as a few other small things

### CODE REVIEW

**Review by calvinrp — APPROVED** [review]

**Comment by lann** [comment]
This looks fine but I'm not sure what makes these changes necessary?

**Comment by thomastaylor312** [comment]
Blocking IO in an async context can cause deadlocks and other weird bugs (ask me how I know!). Also, I think generally going back and cleaning up some code is always a good reason for a PR 😄

**Comment by lann** [comment]
Ah ok. I just ask because I've been freely mixing async and sync here under the assumption that it shouldn't make any difference for this sort of cli tool 🤷

**Comment by thomastaylor312** [comment]
It _shouldn't_ but I've been bit one too many times

**Comment by thomastaylor312** [comment]
I'd really like to follow best practices here if we can unless we're sure we're ok with taking that risk on

**Comment by thomastaylor312** [comment]
@lann I did some more looking and I retract my previous statement. I think because these are running serially, we're ok. We might need to use them in the other crates since they're libraries and could be used in parallel with other IO bound tasks

**Pull request closed without merging**
